steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: next-market-repo
  _IMAGE: next-market
  _TAG: latest
